USE ventas_jugos;

CREATE TABLE tb_vendedor (
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) NULL,
BARRIO VARCHAR(50) NULL,
COMISION FLOAT NULL,
FECHA_ADMISION DATE NULL,
DE_VACACIONES BIT(1) NULL,
PRIMARY KEY(MATRICULA)
);

CREATE TABLE tb_productos(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANO VARCHAR(50) NULL,
ENVASE VARCHAR(50) NULL,
PRECIO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

CREATE TABLE clientes (
DNI varchar(11) NOT NULL,
NOMBRE varchar(100) DEFAULT NULL,
DIRECCION varchar(150) DEFAULT NULL,
BARRIO varchar(50) DEFAULT NULL,
CIUDAD varchar(50) DEFAULT NULL,
ESTADO varchar(45) DEFAULT NULL,
CP varchar(8) DEFAULT NULL,
FECHA_NACIMIENTO date DEFAULT NULL,
EDAD int(2) DEFAULT NULL,
SEXO varchar(1) DEFAULT NULL,
LIMITE_CREDITO float DEFAULT NULL,
VOLUMEN_COMPRA float DEFAULT NULL,
PRIMERA_COMPRA bit(1) DEFAULT NULL,
PRIMARY KEY (DNI)
);

CREATE TABLE `ventas_jugos`.`facturas` (
  `NUMERO` VARCHAR(5) NOT NULL,
  `FECHA` DATE NULL,
  `DNI` VARCHAR(11) NOT NULL,
  `MATRICULA` VARCHAR(5) NOT NULL,
  `IMPUESTO` FLOAT NULL,
  PRIMARY KEY (`NUMERO`));

