USE VENTAS_JUGOS;

SELECT * FROM JUGOS_VENTAS.tabla_de_productos;

SELECT CODIGO_DEL_PRODUCTO AS CODIGO, NOMBRE_DEL_PRODUCTO AS DESCRIPCION,
SABOR, TAMANO, ENVASE, PRECIO_DE_LISTA AS PRECIO_LISTA
FROM jugos_ventas.tabla_de_productos
WHERE CODIGO_DEL_PRODUCTO NOT IN (SELECT CODIGO FROM tb_productos);

INSERT INTO tb_productos
SELECT CODIGO_DEL_PRODUCTO AS CODIGO, NOMBRE_DEL_PRODUCTO AS DESCRIPCION,
SABOR, TAMANO, ENVASE, PRECIO_DE_LISTA AS PRECIO_LISTA
FROM jugos_ventas.tabla_de_productos
WHERE CODIGO_DEL_PRODUCTO NOT IN (SELECT CODIGO FROM tb_productos);

SELECT * FROM tb_productos;

TRUNCATE tb_productos;

SELECT * FROM tb_items_facturas;

TRUNCATE tb_productos;

SHOW CREATE TABLE tb_items_facturas;

CREATE TABLE `tb_items_facturas` (
   `NUMERO` varchar(5) NOT NULL,
   `CODIGO` varchar(10) NOT NULL,
   `CANTIDAD` int DEFAULT NULL,
   `PRECIO` float DEFAULT NULL,
   PRIMARY KEY (`NUMERO`,`CODIGO`),
   KEY `FK_PRODUCTO` (`CODIGO`),
   CONSTRAINT `FK_PRODUCTO` FOREIGN KEY (`CODIGO`) REFERENCES `tb_productos` (`CODIGO`) ON DELETE CASCADE
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE tb_items_facturas DROP FOREIGN KEY FK_PRODUCTO;

ALTER TABLE tb_items_facturas ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY(CODIGO) REFERENCES tb_productos(CODIGO) ON DELETE CASCADE;

TRUNCATE tb_productos;

SELECT * FROM tb_cliente;

INSERT INTO tb_cliente
SELECT DNI, NOMBRE, DIRECCION_1 AS DIRECCION,
BARRIO, CIUDAD, ESTADO, CP, FECHA_DE_NACIMIENTO 
AS FECHA_NACIMIENTO, EDAD, SEXO, LIMITE_DE_CREDITO
AS LIMITE_CREDITO, VOLUMEN_DE_COMPRA AS VOLUMEN_COMPRA,
PRIMERA_COMPRA FROM jugos_ventas.tabla_de_clientes
WHERE DNI NOT IN (SELECT DNI FROM tb_cliente);

SELECT DNI, NOMBRE, DIRECCION_1 AS DIRECCION,
BARRIO, CIUDAD, ESTADO, CP, FECHA_DE_NACIMIENTO AS
FECHA_NACIMIENTO, EDAD, SEXO, LIMITE_DE_CREDITO
AS LIMITE_CREDITO, VOLUMEN_DE_COMPRA AS VOLUMEN_COMPRA,
PRIMERA_COMPRA FROM jugos_ventas.tabla_de_clientes
WHERE DNI NOT IN (SELECT DNI FROM ventas_jugos.tb_cliente);

INSERT INTO tb_cliente
SELECT DNI, NOMBRE, DIRECCION_1 AS DIRECCION,
BARRIO, CIUDAD, ESTADO, CP, FECHA_DE_NACIMIENTO AS
FECHA_NACIMIENTO, EDAD, SEXO, LIMITE_DE_CREDITO
AS LIMITE_CREDITO, VOLUMEN_DE_COMPRA AS VOLUMEN_COMPRA,
PRIMERA_COMPRA FROM jugos_ventas.tabla_de_clientes
WHERE DNI NOT IN (SELECT DNI FROM ventas_jugos.tb_cliente);

SELECT * FROM tb_cliente;

TRUNCATE tb_cliente;

SHOW CREATE TABLE tb_factura;

CREATE TABLE `tb_factura` (
   `NUMERO` varchar(5) NOT NULL,
   `FECHA` date DEFAULT NULL,
   `DNI` varchar(11) NOT NULL,
   `MATRICULA` varchar(5) NOT NULL,
   `IMPUESTO` float DEFAULT NULL,
   PRIMARY KEY (`NUMERO`),
   KEY `FK_CLIENTE` (`DNI`),
   KEY `FK_VENDEDOR` (`MATRICULA`),
   CONSTRAINT `FK_CLIENTE` FOREIGN KEY (`DNI`) REFERENCES `tb_cliente` (`DNI`),
   CONSTRAINT `FK_ITEM_FACTURAS` FOREIGN KEY (`NUMERO`) REFERENCES `tb_items_facturas` (`NUMERO`),
   CONSTRAINT `FK_VENDEDOR` FOREIGN KEY (`MATRICULA`) REFERENCES `tb_vendedor` (`MATRICULA`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
 
ALTER TABLE tb_factura DROP FOREIGN KEY FK_CLIENTE;
ALTER TABLE tb_factura DROP FOREIGN KEY FK_ITEM_FACTURAS;
ALTER TABLE tb_factura DROP FOREIGN KEY FK_VENDEDOR;

ALTER TABLE tb_factura ADD CONSTRAINT `FK_CLIENTE` FOREIGN KEY (`DNI`) REFERENCES `tb_cliente` (`DNI`);
ALTER TABLE tb_factura ADD CONSTRAINT `FK_ITEM_FACTURAS` FOREIGN KEY (`NUMERO`) REFERENCES `tb_items_facturas` (`NUMERO`);
ALTER TABLE tb_factura ADD CONSTRAINT `FK_VENDEDOR` FOREIGN KEY (`MATRICULA`) REFERENCES `tb_vendedor` (`MATRICULA`);

SELECT * FROM tb_vendedor
