SELECT A.CODIGO_DEL_PRODUCTO, C.CANTIDAD FROM tabla_de_productos A
INNER JOIN items_facturas C
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO;

SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS ANNO, C.CANTIDAD FROM tabla_de_productos A
INNER JOIN items_facturas C
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO
INNER JOIN facturas B
ON C.NUMERO = B.NUMERO;

SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS ANNO, SUM(C.CANTIDAD) AS CANTIDAD FROM tabla_de_productos A
INNER JOIN items_facturas C
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO
INNER JOIN facturas B
ON C.NUMERO = B.NUMERO
GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA)
ORDER BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA);

-- COST 4.50
SELECT A.CODIGO_DEL_PRODUCTO FROM tabla_de_productos A;

-- COST 84866.54
SELECT A.CODIGO_DEL_PRODUCTO, C.CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO;

-- COST 138676.67
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS ANNO, C.CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas B ON C.NUMERO = B.NUMERO;

-- COST 138676.67
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS ANNO, SUM(C.CANTIDAD) AS CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas B ON C.NUMERO = B.NUMERO GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) ORDER BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA);

-- COST 8849.05
-- EXPLAIN FORMAT=JSON SELECT * FROM FACTURAS WHERE FECHA_VENTA = '20170101' \G;

-- COST 25.90
-- ALTER TABLE FACTURAS ADD INDEX(FECHA_VENTA);

-- COST 8849.05
-- ALTER TABLE FACTURAS DROP INDEX FECHA_VENTA;