SELECT A.FECHA, SUM(B.CANTIDAD*B.PRECIO) AS FACTURACION
FROM facturas A
INNER JOIN 
items B
ON A.NUMERO = B.NUMERO
WHERE A.FECHA = '20210619'
GROUP BY A.FECHA;

CALL sp_venta('20210619', 3, 100);

SELECT COUNT(*) FROM productos;

CALL sp_venta('20210619', 100, 100);

SELECT YEAR(FECHA), CEIL(SUM(IMPUESTO * (CANTIDAD * PRECIO))) 
AS RESULTADO
FROM facturas F
INNER JOIN items I ON F.NUMERO = I.NUMERO
WHERE YEAR(FECHA) = 2021
GROUP BY YEAR(FECHA);